### ISSUE TITLE
Error in children page endpoint

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1222]
### Describe the Bug

When a page is opened in the app that does not have a public parent page, the children endpoint returns an error

### Steps to Reproduce

1. Create parent page without translation in a specific language
2. Create a sub page with a translation in this language
3. Access children endpoint

### Expected Behavior

Not sure what the expected output is here. Should we not show anything because the page is also hidden from the category view, or should we create the impression that the page would be a root page?

### Actual Behavior

```
Feb 21 21:23:13 ERROR   django.request - Internal Server Error: /gemeinschaftsunterkunft/en/wp-json/extensions/v3/children/
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/decorators.py", line 164, in wrap
    return func(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/decorators.py", line 124, in wrap
    return function(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/v3/pages.py", line 205, in children
    result.append(transform_page(public_translation))
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/v3/pages.py", line 24, in transform_page
    parent_absolute_url = parent_page.get_public_translation(
AttributeError: 'NoneType' object has no attribute 'get_absolute_url'
Feb 21 21:23:13 WARNING django.request - Not Found: /gemeinschaftsunterkunft/en/wp-json/extensions/v3/parents/
```

### Additional Information

If we decide to show nothing, we have to make sure that the `available_languages` mapping of all other translations of this page do not contain this translation.

**Comment by svenseeberg** [comment]
```
Feb 21 21:38:37 ERROR   django.request - Internal Server Error: /juergenstorf/de/wp-json/extensions/v3/children/
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/decorators.py", line 178, in wrap
    return func(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/decorators.py", line 124, in wrap
    return function(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/v3/pages.py", line 205, in children
    result.append(transform_page(public_translation))
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/v3/pages.py", line 22, in transform_page
    parent_page = page_translation.page.cached_parent
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/models/abstract_tree_node.py", line 210, in cached_parent
    return self.get_cached_ancestors()[-1]
IndexError: list index out of range
```

**Comment by svenseeberg** [comment]
Solution: don't link translations where parents have no existing translation.

**Comment by svenseeberg** [comment]
Also part of this bug: archived pages are returned in the result.
