### ISSUE TITLE
Error when saving page

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1316]
### Describe the Bug

Probably caused by #1320. Trace:

```
ar 22 12:06:43 ERROR   django.request - Internal Server Error: /schneeberg/pages/de/3242/edit/
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/views/pages/page_form_view.py", line 262, in post
    page_translation_form.instance.page = page_form.save()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/forms/custom_model_form.py", line 132, in save
    return super().save(commit=commit)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/treebeard/forms.py", line 157, in save
    self.instance.move(reference_node, pos=position_type)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/models/abstract_tree_node.py", line 285, in move
    super().move(target=target, pos=pos)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/treebeard/ns_tree.py", line 357, in move
    if target.is_descendant_of(self):
AttributeError: 'NoneType' object has no attribute 'is_descendant_of'
```

**Comment by svenseeberg** [comment]
Duplicate of #1320
