### ISSUE TITLE
Error when loading page tree

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1317]
### Describe the Bug

Probably caused by #1320. Trace:

```
Mar 22 12:05:27 ERROR   django.request - Internal Server Error: /viersen/ajax/render/partial-page-tree/de/tree-579/
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/views/pages/partial_page_tree_view.py", line 48, in get
    parent = pages[0]
IndexError: list index out of range
```

**Comment by svenseeberg** [comment]
Duplicate of #1320
