### ISSUE TITLE
Error when creating page

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1318]
### Describe the Bug

Needs to be reproduced. Trace:

```
Mar 22 11:57:21 ERROR   django.request - Internal Server Error: /schneeberg/pages/de/new/
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/views/pages/page_form_view.py", line 262, in post
    page_translation_form.instance.page = page_form.save()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/forms/custom_model_form.py", line 132, in save
    return super().save(commit=commit)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/treebeard/forms.py", line 148, in save
    self.instance = reference_node.add_child(**cl_data)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/models/abstract_tree_node.py", line 64, in add_child
    child = super().add_child(**kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/treebeard/ns_tree.py", line 199, in add_child
    last_child._cached_parent_obj = self
AttributeError: 'NoneType' object has no attribute '_cached_parent_obj'
```

**Comment by svenseeberg** [comment]
Same error again due to broken tree_id:
```
  id  |         created_date          | explicitly_archived | lft | rgt | tree_id | depth | mirrored_page_first | icon_id | mirrored_page_id | organization_id | parent_id | region_id | api_token 
------+-------------------------------+---------------------+-----+-----+---------+-------+---------------------+---------+------------------+-----------------+-----------+-----------+-----------
 3300 | 2022-03-28 10:39:38.571114+00 | f                   |   2 |   3 |     929 |     2 | f                   |         |             2759 |                 |      3299 |       165 | 
 3301 | 2022-03-28 10:40:18.186689+00 | f                   |   4 |   5 |     929 |     2 | f                   |         |             2761 |                 |      3299 |       165 | 
 3299 | 2022-03-28 10:39:04.33347+00  | f                   |   1 |   6 |     930 |     1 | f                   |   18628 |             2760 |                 |           |       165 | 
 ```

**Comment by svenseeberg** [comment]
Duplicate of #1320
