### ISSUE TITLE
Event validation throws `KeyError` when dates are invalid

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1705]
### Describe the Bug

When the event form is submitted without an invalid start or end date, the form throws an internal server error instead of showing an informative error message.

### Steps to Reproduce

Not sure how to reproduce this, one way to simulate it would be to remove the `required` html attribute in the browser's dev tools and submit the form.

### Expected Behavior

There should be an informative error message, e.g. "start date is missing" or "start date: xyz is an invalid date format" or similar... This usually happens in Django by default, but in this case the custom `clean()` method breaks the default validation.

### Actual Behavior

An internal server error is thrown (`KeyError: 'end_date'`)

### Additional Information

This is a similar problem like #1656.
Use `cleaned_data.get("end_date"),` instead of `cleaned_data["end_date"],` to prevent the key error...

<details>
  <summary>Traceback</summary>

  ```
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/views/events/event_form_view.py", line 171, in post
    event_form_valid = event_form.is_valid()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/forms/forms.py", line 373, in full_clean
    self._clean_form()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/forms/forms.py", line 400, in _clean_form
    cleaned_data = self.clean()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/forms/events/event_form.py", line 187, in clean
    cleaned_data["end_date"],
KeyError: 'end_date'
  ```

</details>

**Comment by devbazregari** [comment]
hi bro I hope you're doing great.  in which file do you want to implement this logic?

**Comment by timoludwig** [comment]
@devbazregari Great to hear you want to tackle another issue :muscle: 
As you can see, this issue is already assigned and has an [open PR]( #1706). So no need to implement another solution for it.

You can find other good first issues which aren't assigned yet by typing the following in the issue list:

[is:open is:issue label:"good first issue" no:assignee ](https://github.com/digitalfabrik/integreat-cms/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee)

**Comment by devbazregari** [comment]
oh , yes. I didn't see it.
sure.
