### ISSUE TITLE
IntegrityError when creating POIs

### ISSUE THREAD

**Issue by PeterNerlich** [digitalfabrik/integreat-cms#1877]
### Describe the Bug
CMS throws IntegrityError

### Steps to Reproduce

1. Check out `bugfix/excape-messages`
2. Go to the *Locations* (POI) view of an existing region
3. Click on *Create Location*
4. Fill out basic required data (put name, street and postal code as `a` and let it autocomplete the rest to Elstertrebnitz, for whatever reason)
5. Click on *Publish*
6. See error

### Expected Behavior
POI is successfully created

### Actual Behavior
POI was not created, django showed the below error trace:

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
Environment:


Request Method: POST
Request URL: http://localhost:8000/augsburg/pois/de/new/

Django Version: 3.2.16
Python Version: 3.9.15
Installed Applications:
['integreat_cms.cms',
 'integreat_cms.deepl_api',
 'integreat_cms.firebase_api',
 'integreat_cms.gvz_api',
 'integreat_cms.nominatim_api',
 'integreat_cms.summ_ai_api',
 'integreat_cms.textlab_api',
 'integreat_cms.linkcheck.apps.ModifiedLinkcheckConfig',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'corsheaders',
 'rules.apps.AutodiscoverRulesConfig',
 'treebeard',
 'webpack_loader',
 'widget_tweaks',
 'polymorphic',
 'django.contrib.admin',
 'debug_toolbar']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'integreat_cms.core.middleware.RegionMiddleware',
 'integreat_cms.core.middleware.AccessControlMiddleware',
 'integreat_cms.core.middleware.TimezoneMiddleware',
 'integreat_cms.api.middleware.JsonDebugToolbarMiddleware']



Traceback (most recent call last):
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (null value in column "opening_hours" of relation "cms_poi" violates not-null constraint
DETAIL:  Failing row contains (11, 2022-11-18 14:13:48.775222+00, a, 04523, Elstertrebnitz, Deutschland, 51.1554783, 12.241476, f, f, null, 1, , , , null, null, null).
) was the direct cause of the following exception:
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/integreat_cms/cms/views/pois/poi_form_view.py", line 169, in post
    poi_translation_form.instance.poi = poi_form.save()
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/integreat_cms/cms/forms/custom_model_form.py", line 132, in save
    return super().save(commit=commit)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/forms/models.py", line 468, in save
    self.instance.save()
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/debug_toolbar/panels/sql/tracking.py", line 230, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/debug_toolbar/panels/sql/tracking.py", line 154, in _record
    return method(sql, params)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/peter/NewStructure/Projects/Code/integreat-cms/.venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: IntegrityError at /augsburg/pois/de/new/
Exception Value: null value in column "opening_hours" of relation "cms_poi" violates not-null constraint
DETAIL:  Failing row contains (11, 2022-11-18 14:13:48.775222+00, a, 04523, Elstertrebnitz, Deutschland, 51.1554783, 12.241476, f, f, null, 1, , , , null, null, null).
  ```

</details>

**Comment by timoludwig** [comment]
This is a pretty normal behavior: Your database schema always needs to adapt after each branch change, otherwise you will get inconsistencies. So when you notice such an error, first reset your database and run the migrations again to make sure the problem is not caused by your local setup.

**Comment by PeterNerlich** [comment]
I see. How is this handled in production, when the existing database should not be completely recreated? Or is this a consequence of jumping back and forth between different points in development which are not directly related through the migration records?

**Comment by timoludwig** [comment]
> Or is this a consequence of jumping back and forth between different points in development which are not directly related through the migration records?

Yes, exactly that! On production, we never check out different branches, we just run the migrations which make it to the develop branch and treat them as the single source of truth. And once the migrations end up on the develop branch, we do not change them again to make sure the database on the production system does not get into an inconsistent state.
