### ISSUE TITLE
Broken images cause PDF export to fail

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2356]
### Describe the Bug

When an image is broken, it causes the complete PDF export to fail

### Steps to Reproduce

https://integreat.app/testumgebung/de/test-broken-photo-pdf
https://cms.integreat-app.de/testumgebung/de/wp-json/ig-mpdf/v1/pdf?url=%2Ftestumgebung%2Fde%2Ftest-broken-photo-pdf

### Expected Behavior

We should ignore the image or show a placeholder, but generate the PDF

### Actual Behavior

An internal server error occurs

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
Jul 23 22:12:01 WARNING integreat_cms.cms.utils.pdf_utils - The file 'https://integreat.app/dortmund
/wp-content/uploads/sites/187/2017/11/calendar60-1.png' is not inside the static directories '/stati
c/' and '/media/'.
Jul 23 22:12:03 WARNING xhtml2pdf - Error in handling image
'<img class="alignnone wp-image-589" src="https://integreat.app/dortmund/wp-content/uploads/sites/187/2017/11/calendar60-1.png" alt="" width="15" height="15" dir="rtl"/>'
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 323, in __init__
    self._image = self._read_image(self.fp)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 353, in _read_image
    return PILImage.open(fp)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/PIL/Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fcde76a5360> fileName=<_io.BytesIO object at 0x7fcde76a5360>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/xhtml2pdf/tags.py", line 354, in start
    img = PmlImage(
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 467, in __init__
    img = self.getImage()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 528, in getImage
    img = PmlImageReader(imgdata)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 342, in __init__
    raise RuntimeError("{0} {1} {2}".format(et, ev, tb))
RuntimeError: <class 'PIL.UnidentifiedImageError'> cannot identify image file <_io.BytesIO object at 0x7fcde76a5360> fileName=<_io.BytesIO object at 0x7fcde76a5360> <traceback object at 0x7fcde7fd5c00>
  ```

</details>

**Comment by timobrembeck** [comment]
I decided to fix this problem in the upstream library:
https://github.com/xhtml2pdf/xhtml2pdf/pull/723

It will take a while until we can profit from this change, since updating is blocked at the moment (see  #2047), but eventually we will get there :smile:
