### ISSUE TITLE
`TypeError`: `>` not supported between instances of `NoneType` and `NoneType`

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2449]
### Describe the Bug

#2419 introduced a new bug despite the tests were successful on the PR (yet another reason why we need #2060)

### Steps to Reproduce
https://app.circleci.com/pipelines/github/digitalfabrik/integreat-cms/9650/workflows/063d1449-2c90-4a7c-b98f-29558433e126/jobs/107953

### Expected Behavior

No error

### Actual Behavior

```
TypeError: 'Region' object is not subscriptable

During handling of the above exception, another exception occurred:

TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
Traceback (most recent call last):
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'Region' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/circleci/project/integreat_cms/cms/views/regions/region_list_view.py", line 58, in get
    return render(
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/circleci/project/.venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/circleci/project/integreat_cms/cms/models/regions/region.py", line 849, in last_content_update
    return max(
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
  ```

</details>

**Comment by timobrembeck** [comment]
Unfortunately, I did not fix this error completely, and it is on the live system now :(
```
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/models/regions/region.py", line 860, in last_content_update
    return max(
TypeError: '>' not supported between instances of 'NoneType' and 'datetime.datetime'
```

**Comment by timobrembeck** [comment]
Ok, I found the culprit: There were a few regions in the production database which had an imprint set without translations. This is why the if condition did not work as intended.
I deleted the inconsistent imprints now, so this is no longer urgent.
Still makes sense to prevent this error in the future, but in general I think we can assume that our database is consistent.

**Comment by charludo** [comment]
Super sorry, I should have realized other content than the imprint might be empty as well 🙈
