### ISSUE TITLE
Internal Server Error when creating password from email link

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#2484]
### Describe the Bug
An internal server error occurs when I try to create a password for a new account via the link sent in the activation email

### Steps to Reproduce

1. Start creating a new user with an email you have access to
2. Check the box next to "send activation link"
3. Create user
4. Open link in Email
5. put in new password
6. click save
7. See error

### Expected Behavior
A password is created an d I can log in

### Actual Behavior
Internal Server Error, password not saved

**Comment by timobrembeck** [comment]
This is the traceback:
```Oct 26 08:45:19 ERROR   django.request - 500 Internal Server Error: /reset-password/NzY5/set-password/
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/views/authentication/password_reset_confirm_view.py", line 42, in dispatch
    response = super().dispatch(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/views.py", line 272, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/views/authentication/password_reset_confirm_view.py", line 73, in form_valid
    " ".join(
TypeError: sequence item 0: expected str instance, __proxy__ found
```
So this is most likely a regression from #2454.
