### ISSUE TITLE
`TypeError: expected string or bytes-like object` in nominatim API client

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2495]
### Steps to Reproduce

1. Go to https://admin.integreat-app.de/testumgebung-reg/pois/de/new/
2. Input something ?
3. Submit form

### Expected Behavior

A POI should be created and the coordinates should correctly be retrieved from the nominatim api

### Actual Behavior

An internal server error occurs

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
Oct 30 09:30:52 ERROR   django.request - 500 Internal Server Error: /testumgebung-reg/pois/de/new/
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/views/pois/poi_form_view.py", line 166, in post
    if not poi_form.is_valid() or not poi_translation_form.is_valid():
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/forms/forms.py", line 373, in full_clean
    self._clean_form()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/forms/forms.py", line 400, in _clean_form
    cleaned_data = self.clean()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/forms/pois/poi_form.py", line 164, in clean
    latitude, longitude = nominatim_api_client.get_coordinates(
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/nominatim_api/nominatim_api_client.py", line 134, in get_coordinates
    if result := self.search(street=street, postalcode=postalcode, city=city):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/nominatim_api/nominatim_api_client.py", line 80, in search
    query_dict["street"] = re.sub(
  File "/usr/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
  ```

</details>

**Comment by timobrembeck** [comment]
This is not a new bug, but seems to exist for a while and just occurs in some edge cases.

**Comment by JoeyStk** [comment]
I tried to find out what the two municipalities did on that date to exactly reproduce it. It only helped me a bit. I noticed that they tried to create 

- a POI from the event form
- a POI without an exact address number (street name 22-24)
- a POI in the others category

But I still wasn't able to reproduce it. Maybe one other person can try to reproduce it, and then it might be best to ask the service to ask the municipalities what they were trying to do? :/

**Comment by timobrembeck** [comment]
It would also be interesting to know who tried to create a poi in the testumgebung today at 09:30:52 UTC...

**Comment by JoeyStk** [comment]
testumgebung-reg? That would have been me. Why? Did the problem occur at time again?

**Comment by timobrembeck** [comment]
> testumgebung-reg? That would have been me. Why? Did the problem occur at time again?

Yes, this was the original reason why I created the ticket, see the initial traceback of the bug

**Comment by JoeyStk** [comment]
Ah no, then it wasn't me. I started to reproduce it just after you created the issue. Must have been more like 11:40 then. Ok, then I'm not able to reproduce it

**Comment by MizukiTemma** [comment]
How to reproduce: space in "Street and house number"
