### ISSUE TITLE
Internal Server Error when accessing Machine Translations in cms-test

### ISSUE THREAD

**Issue by PeterNerlich** [digitalfabrik/integreat-cms#2510]
### Describe the Bug

When navigating to the *Machine Translations* section of a region on *cms-test*, it results in a `500 Internal Server Error`.

### Steps to Reproduce

1. Go to the dashboard of any region with machine translations enabled
2. Click on *Machine Translations*

*I have not been able to reproduce this locally yet.*

### Expected Behavior

The machine translation dashboard shows as normal.

### Actual Behavior

`500 Internal Server Error`

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
Oct 31 15:20:39 ERROR   django.request - 500 Internal Server Error: /muenchen/translations/manage/
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/views/translations/translations_management_view.py", line 106, in get
    **self.get_context_data(**kwargs),
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/cms/views/translations/translations_management_view.py", line 61, in get_context_data
    for content in contents:
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/cacheops/query.py", line 261, in _fetch_all
    self._cache_results(cache_key, self._result_cache)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/cacheops/query.py", line 179, in _cache_results
    cache_thing(self._prefix, cache_key, results,
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/cacheops/redis.py", line 16, in handle_connection_failure
    return call()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/cacheops/getset.py", line 47, in cache_thing
    settings.CACHEOPS_SERIALIZER.dumps(data),
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 233, in __getstate__
    self._fetch_all()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/cacheops/query.py", line 252, in _fetch_all
    cache_key = self._cache_key()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/cacheops/query.py", line 152, in _cache_key
    sql, params = self.query.get_compiler(self.db).as_sql()
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 528, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 445, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/sql/where.py", line 81, in as_sql
    sql, params = compiler.compile(child)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 445, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 194, in as_sql
    rhs_sql, rhs_params = self.process_rhs(compiler, connection)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 99, in process_rhs
    return compiler.compile(value)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 445, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/expressions.py", line 603, in as_sql
    raise ValueError(
ValueError: This queryset contains a reference to an outer query and may only be used in a subquery.
  ```

</details>

**Comment by MizukiTemma** [comment]
How to reproduce locally: activate Redis ☝️
