### ISSUE TITLE
Fix the error message when deleting a media file in use

### ISSUE THREAD

**Issue by seluianova** [digitalfabrik/integreat-cms#2585]
### Describe the Bug
When deleting a media file that is in use, a network error is displayed
![image](https://github.com/digitalfabrik/integreat-cms/assets/115008338/7a7371aa-ff98-4fe8-88a9-eccd5659b3e0)

### Steps to Reproduce

1. Go to 'Media Library'
2. Try to delete a media file that is being used as the organisation icon
3. See error

### Expected Behavior
I think we could display a more understandable (user-friendly) message.
Like: "This media file can't be deleted because it is in use"

### Actual Behavior
The following error is displayed:
A network error has occurred. Please try again later.

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
Dec 06 11:32:21 ERROR django.request - 500 Internal Server Error: /ajax/media/file/delete/
Traceback (most recent call last):
  File "/home/tory/Integreat/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tory/Integreat/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tory/Integreat/integreat-cms/.venv/lib/python3.9/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/tory/Integreat/integreat-cms/.venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/tory/Integreat/integreat-cms/integreat_cms/api/decorators.py", line 115, in wrap
    return function(request, *args, **kwargs)
  File "/home/tory/Integreat/integreat-cms/integreat_cms/cms/views/media/media_actions.py", line 361, in delete_file_ajax
    media_file.delete()
  File "/home/tory/Integreat/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 966, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/home/tory/Integreat/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/deletion.py", line 302, in collect
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'MediaFile' because they are referenced through protected foreign keys: 'Organization.icon'.", {<Organization (id: 1, slug: test-organization, region: augsburg)>})
  ```

</details>

**Comment by seluianova** [comment]
I am not sure about the expected result actually. 
Maybe we should be able to delete used media files actually? And there should be no error in this case?

**Comment by seluianova** [comment]
I am not sure about the expected result actually.
Maybe there should be no error in this case? And we should be able to delete used media files?

**Comment by MizukiTemma** [comment]
> If so, what do we do with organisations, where the logo is mandatory, and the deleted file was used as a logo?

That's why we want to prevent media files from being deleted when they are used. But I agree with you that just showing an error  is not user friendly 😅 

> Or maybe we should disable the "delete" button in this case, and show a tooltip message?

I think disabling is the best. The reason can be explained like for archiving a mirrored page:

![example](https://github.com/digitalfabrik/integreat-cms/assets/82345046/ae5e3703-b3f9-442c-8a35-0da9d15bd497)
